version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pokedex-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokedex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokedex-net

volumes:
  postgres_data:
    driver: local

networks:
  pokedex-net:
    driver: bridge
